- name: Copy file from host machine to client hosts
  hosts: pi
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Copy file from host to client
      ansible.builtin.copy:
        src: /folder/worked.txt
        dest: /home/pi/Downloads/worked.txt
