- name: Copy file from host machine to client hosts
  hosts: pi
  tasks:
    - name: Copy file from host to client
      ansible.builtin.copy:
        src: /home/gorlock/folder/worked.txt
        dest: /home/pi/Downloads/worked.txt
      vars:
       ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
