---
tasks:
  - name: Debug source path
    ansible.builtin.debug:
      msg: "Source path is {{ src }}"

  - name: Copy file from host to client
    ansible.builtin.copy:
      src: /home/gorlock/folder/worked.txt
      dest: /home/pi/Downloads/worked.txt
