- name: Copy file from host machine to client hosts
  hosts: clients
  tasks:
    - name: Copy file from host to client
      ansible.builtin.copy:
        src: /home/gorlock/folder/worked.txt
        dest: /home/{{ ansible_user }}/Downloads/worked.txt
