---
- name: Copy file from host machine to client hosts
  hosts: pi
  vars:
    ansible_host_key_checking: false
  tasks:    
    - name: Copy file from host to client
      ansible.builtin.get_url:
          url: "https://raw.githubusercontent.com/netvault/ansible-test/main/new.txt"  # Replace this with the actual URL
          dest: "/home/pi/Downloads/worked.txt"
